version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/finance_db
    depends_on:
      - mongodb
